name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: actions/checkout@v3
      - run: npm i -g pnpm
      - run: pnpm i

      - name: Build Astro
        run: pnpm run build
        env:          
          PRIVATE_SIB_KEY: ${{ secrets.sibApiKey }}
          PRIVATE_TO_EMAIL: ${{ secrets.toEmail }}
          PRIVATE_TO_NAME: ${{ secrets.toName }}
          PRIVATE_FROM_EMAIL: ${{ secrets.fromEmail }}
          PRIVATE_FROM_NAME: ${{ secrets.fromName }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: c00-covle-com
          entrypoint: server/entry.mjs
          root: dist